using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace VeloxMapper.Generators;

/// <summary>
/// Projedeki [VeloxMap(typeof(Source), typeof(Dest))] bildirimlerini tarayarak
/// derleme zamanında NativeAOT uyumlu, sıfır maliyetli ve deterministik mapping kodu üretir.
/// Layer 1 — Source Generator.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MapperGenerator : IIncrementalGenerator
{
    /// <summary>VM003: [VeloxMap] çifti için derleme zamanı kodu üretilemedi (çalışma zamanı motoru kullanılır).</summary>
    public static readonly DiagnosticDescriptor UnsupportedMappingRule = new(
        id: "VM003",
        title: "Derleme zamanı eşlemesi üretilemedi",
        messageFormat: "'{0}' -> '{1}' için derleme zamanı eşlemesi üretilemedi: {2}. Bu çift çalışma zamanı motoruyla eşlenmeye devam eder.",
        category: "VeloxMapper.Design",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // [VeloxMap] attribute'larını tara.
        // ForAttributeWithMetadataName, her attribute kullanımı için bir kez tetiklenir.
        // GetAllMappingInfos → IEnumerable döner; SelectMany ile her MappingInfo ayrı entry olur.
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "VeloxMapper.Attributes.VeloxMapAttribute",
                predicate: static (node, _) => true,
                transform: static (ctx, _) => GetAllMappingInfos(ctx))
            .SelectMany(static (infos, _) => infos); // IEnumerable<MappingInfo> → düzleştir

        // Tüm mapping bilgileri için tek bir kaynak dosya üret
        context.RegisterSourceOutput(provider.Collect(), static (spc, mappings) =>
        {
            if (mappings.IsDefaultOrEmpty) return;

            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated />");
            sourceBuilder.AppendLine("// VeloxMapper Source Generator v4.0 — Bu dosyayı düzenlemeyin.");
            sourceBuilder.AppendLine("#nullable enable");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("using System;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("namespace VeloxMapper.Generated");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    /// <summary>");
            sourceBuilder.AppendLine("    /// Derleme zamanında üretilmiş, NativeAOT uyumlu, saf (pure) mapper metotları.");
            sourceBuilder.AppendLine("    /// </summary>");
            sourceBuilder.AppendLine("    public static partial class GeneratedMappers");
            sourceBuilder.AppendLine("    {");

            // Distinct ile aynı çiftin birden fazla kez üretilmesini önle
            foreach (var mapping in mappings.Distinct())
            {
                if (mapping.SkipReason != null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(UnsupportedMappingRule, Location.None, mapping.SourceFullName, mapping.DestinationFullName, mapping.SkipReason));
                    continue;
                }

                GenerateMappingMethod(sourceBuilder, mapping);
            }

            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");

            spc.AddSource("VeloxMapper.Generated.g.cs",
                SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Bir kaynak üye değerini hedef türe uygun ifade olarak yazar (Nullable açma, enum cast).
    /// </summary>
    private static string FormatValue(PropertyMapping pm)
    {
        var value = pm.NeedsNullCoalescing ? $"source.{pm.SourceName} ?? default" : $"source.{pm.SourceName}";
        if (pm.NeedsEnumCast && !string.IsNullOrEmpty(pm.DestTypeFullName)) value = $"({pm.DestTypeFullName})({value})";
        return value;
    }

    /// <summary>
    /// Tek bir kaynak→hedef çifti için static extension method üretir.
    /// </summary>
    private static void GenerateMappingMethod(StringBuilder sb, MappingInfo mapping)
    {
        // Nokta ve generik karakterleri kaldırarak geçerli bir C# metot adı oluştur
        var safeName = mapping.DestinationFullName
            .Replace(".", "")
            .Replace("<", "")
            .Replace(">", "")
            .Replace(",", "")
            .Replace(" ", "");

        var methodName = $"MapTo{safeName}";

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// {mapping.SourceFullName} \u2192 {mapping.DestinationFullName} derleme zaman\u0131 e\u015fle\u015ftirmesi.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static {mapping.DestinationFullName} {methodName}(this {mapping.SourceFullName} source)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(source);");

        var ctorArgs = string.Join(", ", mapping.ConstructorArguments.Select(FormatValue));
        sb.Append($"            return new {mapping.DestinationFullName}({ctorArgs})");

        if (mapping.PropertyMappings.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            {");
            for (int i = 0; i < mapping.PropertyMappings.Length; i++)
            {
                var pm = mapping.PropertyMappings[i];
                var comma = i < mapping.PropertyMappings.Length - 1 ? "," : "";
                sb.AppendLine($"                {pm.DestName} = {FormatValue(pm)}{comma}");
            }
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine(";");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Bir GeneratorAttributeSyntaxContext içindeki TÜM [VeloxMap] attribute'larını işler.
    /// Her attribute için bir MappingInfo üretir — SelectMany ile düzleştirilmek üzere.
    ///
    /// Düzeltilen kritik hata: Eski kod "foreach + return" ile yalnızca ilk attribute'u işliyordu.
    /// Bu versiyon tüm attribute'ları işleyip liste döner.
    /// </summary>
    private static IEnumerable<MappingInfo> GetAllMappingInfos(GeneratorAttributeSyntaxContext context)
    {
        var result = new List<MappingInfo>();
        var attrs = context.Attributes;

        if (attrs.IsDefaultOrEmpty)
            return result;

        foreach (var attr in attrs)
        {
            if (attr.ConstructorArguments.Length != 2) continue;

            var srcTypeArg = attr.ConstructorArguments[0];
            var dstTypeArg = attr.ConstructorArguments[1];

            if (srcTypeArg.Value is not INamedTypeSymbol srcType) continue;
            if (dstTypeArg.Value is not INamedTypeSymbol dstType) continue;

            var srcProps = GetPublicProperties(srcType);
            var dstProps = GetPublicProperties(dstType);

            var srcFullName = srcType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
            var dstFullName = dstType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");

            if (dstType.IsAbstract || dstType.TypeKind == TypeKind.Interface)
            {
                result.Add(MappingInfo.Skipped(srcFullName, dstFullName, "hedef tür soyut veya arayüz"));
                continue;
            }

            // Kurucu seçimi: parametresiz kurucu varsa nesne başlatıcı, yoksa parametreleri kaynaktan çözülebilen en geniş kurucu
            var ctorArguments = new List<PropertyMapping>();
            var publicCtors = dstType.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public).ToArray();
            var hasParameterless = dstType.IsValueType || publicCtors.Any(c => c.Parameters.Length == 0);
            if (!hasParameterless)
            {
                IMethodSymbol? chosen = null;
                foreach (var ctor in publicCtors.OrderByDescending(c => c.Parameters.Length))
                {
                    var arguments = new List<PropertyMapping>();
                    foreach (var parameter in ctor.Parameters)
                    {
                        var match = srcProps.FirstOrDefault(s => string.Equals(s.Name, parameter.Name, System.StringComparison.OrdinalIgnoreCase));
                        if (match == null) break;
                        var (ok, coalesce, enumCast, destName) = CheckTypeCompatibility(match.Type, parameter.Type);
                        if (!ok) break;
                        arguments.Add(new PropertyMapping(match.Name, parameter.Name, coalesce, enumCast, destName));
                    }

                    if (arguments.Count == ctor.Parameters.Length)
                    {
                        chosen = ctor;
                        ctorArguments = arguments;
                        break;
                    }
                }

                if (chosen == null)
                {
                    result.Add(MappingInfo.Skipped(srcFullName, dstFullName, "parametreleri kaynaktan çözülebilen public bir kurucu yok"));
                    continue;
                }
            }

            var propertyMappings = new List<PropertyMapping>();

            foreach (var dstProp in dstProps)
            {
                // Yalnızca public setter/init erişimcisi olan ve kurucuya verilmeyen üyeler nesne başlatıcıda atanır
                if (dstProp.SetMethod == null || dstProp.SetMethod.DeclaredAccessibility != Accessibility.Public) continue;
                if (ctorArguments.Any(a => string.Equals(a.DestName, dstProp.Name, System.StringComparison.OrdinalIgnoreCase))) continue;

                // Case-insensitive isim eşleştirmesi
                var srcProp = srcProps.FirstOrDefault(s =>
                    string.Equals(s.Name, dstProp.Name, System.StringComparison.OrdinalIgnoreCase));

                if (srcProp == null) continue;

                var (compat, needsNullCoalescing, needsEnumCast, destTypeFullName) = CheckTypeCompatibility(srcProp.Type, dstProp.Type);
                if (!compat) continue;

                propertyMappings.Add(new PropertyMapping(srcProp.Name, dstProp.Name, needsNullCoalescing, needsEnumCast, destTypeFullName));
            }

            result.Add(new MappingInfo(srcFullName, dstFullName, propertyMappings.ToArray(), ctorArguments.ToArray(), null));
        }

        return result;
    }

    /// <summary>
    /// İki Roslyn tipi arasında Layer 1 uyumluluğunu kontrol eder.
    /// Döner: (uyumlu mu?, nullable-coalescing gerekiyor mu?)
    /// </summary>
    private static (bool IsCompatible, bool NeedsNullCoalescing, bool NeedsEnumCast, string? DestTypeFullName) CheckTypeCompatibility(
        ITypeSymbol srcType, ITypeSymbol dstType)
    {
        // Tam tip eşleşmesi
        if (SymbolEqualityComparer.Default.Equals(srcType, dstType))
            return (true, false, false, null);

        // Nullable<T> → T (örn: int? → int)
        if (srcType is INamedTypeSymbol namedSrc &&
            namedSrc.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            var underlying = namedSrc.TypeArguments[0];
            if (SymbolEqualityComparer.Default.Equals(underlying, dstType))
                return (true, true, false, null);
        }

        // Enum → Enum: herhangi iki enum tipi arasında explicit cast ile dönüşüm (Reviewer bulgusu: İsim kısıtı kaldırıldı)
        if (srcType.TypeKind == TypeKind.Enum && dstType.TypeKind == TypeKind.Enum)
        {
            var destFormat = dstType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return (true, false, true, destFormat);
        }

        return (false, false, false, null);
    }

    /// <summary>
    /// Bir tip'in ve miras aldığı üst sınıfların tüm public, instance, okunabilir property'lerini döndürür.
    /// </summary>
    private static IPropertySymbol[] GetPublicProperties(INamedTypeSymbol type)
    {
        var properties = new List<IPropertySymbol>();
        var currentType = type;

        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            var currentProps = currentType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                            !p.IsStatic &&
                            !p.IsIndexer &&
                            p.GetMethod != null);

            foreach (var prop in currentProps)
            {
                // Aynı isimdeki property'lerin derived seviyesinde ezilmiş (override) veya tekrarlanan olanlarından
                // en alttakini önceliklendiriyoruz (listenin benzersiz kalmasını sağlayarak).
                if (!properties.Any(p => string.Equals(p.Name, prop.Name, System.StringComparison.OrdinalIgnoreCase)))
                {
                    properties.Add(prop);
                }
            }

            currentType = currentType.BaseType;
        }

        return properties.ToArray();
    }
}

/// <summary>
/// Source Generator'dan toplanan mapping bilgisi (immutable).
/// netstandard2.0 uyumluluğu için klasik struct kullanılır.
/// </summary>
internal readonly struct MappingInfo
{
    public string SourceFullName { get; }
    public string DestinationFullName { get; }
    public PropertyMapping[] PropertyMappings { get; }

    /// <summary>Kurucuya sırasıyla verilecek argümanlar (parametresiz kurucuda boş).</summary>
    public PropertyMapping[] ConstructorArguments { get; }

    /// <summary>Kod üretilemiyorsa nedeni (VM003 tanılaması); aksi halde <c>null</c>.</summary>
    public string? SkipReason { get; }

    public MappingInfo(string sourceFullName, string destinationFullName, PropertyMapping[] propertyMappings,
        PropertyMapping[] constructorArguments, string? skipReason)
    {
        SourceFullName = sourceFullName;
        DestinationFullName = destinationFullName;
        PropertyMappings = propertyMappings;
        ConstructorArguments = constructorArguments;
        SkipReason = skipReason;
    }

    public static MappingInfo Skipped(string sourceFullName, string destinationFullName, string reason)
        => new(sourceFullName, destinationFullName, new PropertyMapping[0], new PropertyMapping[0], reason);

    public override bool Equals(object obj)
    {
        return obj is MappingInfo other &&
               SourceFullName == other.SourceFullName &&
               DestinationFullName == other.DestinationFullName;
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return ((SourceFullName?.GetHashCode() ?? 0) * 397) ^
                   (DestinationFullName?.GetHashCode() ?? 0);
        }
    }
}

/// <summary>
/// Tek bir özellik eşleştirmesi bilgisi.
/// </summary>
internal readonly struct PropertyMapping
{
    public string SourceName { get; }
    public string DestName { get; }

    /// <summary>
    /// Kaynak nullable (T?) iken hedef non-nullable (T) olduğunda true.
    /// Generator bu durumda "= source.Prop ?? default" atar.
    /// </summary>
    public bool NeedsNullCoalescing { get; }

    /// <summary>
    /// Farklı namespace'lerde yer alan aynı isimli Enum'lar arasında atama yapıldığında explicit cast gerekir.
    /// </summary>
    public bool NeedsEnumCast { get; }

    /// <summary>
    /// Explicit cast için hedefin tam tip adı.
    /// </summary>
    public string? DestTypeFullName { get; }

    public PropertyMapping(string sourceName, string destName, bool needsNullCoalescing = false, bool needsEnumCast = false, string? destTypeFullName = null)
    {
        SourceName = sourceName;
        DestName = destName;
        NeedsNullCoalescing = needsNullCoalescing;
        NeedsEnumCast = needsEnumCast;
        DestTypeFullName = destTypeFullName;
    }
}
